import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
const PageLoaderWrapper = dynamic(() => import("@/Components/PageLoaderWrapper"));

const Sidebar = dynamic(() => import("@/Components/Sidebar"));


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Marketing Email Orchestrator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundColor:"rgb(223,236,254)"}}>
      <div>
      <Sidebar />
      <PageLoaderWrapper>{children}</PageLoaderWrapper>
    </div>
      </body>
    </html>
  );
}
